apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "3tier-app.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: 3tier-frontend
  template:
    metadata:
      labels:
        app: 3tier-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.frontend.env.API_URL }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: 3tier-frontend
